/* Generated by Yosys 0.15 (git sha1 yosys-0.15, gcc 10.3.0 -fPIC -Os) */

(* hdlname = "\\mkLanaiFrontend" *)
(* top =  1  *)
(* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:93.1-503.10" *)
module mkLanaiFrontend(
`ifdef USE_POWER_PINS
    vccd1,
    vssd1,
`endif
    CLK, RST_N, core_imem_request_put, EN_core_imem_request_put, RDY_core_imem_request_put, EN_core_imem_response_get, core_imem_response_get, RDY_core_imem_response_get, core_dmem_request_put, EN_core_dmem_request_put, RDY_core_dmem_request_put, EN_core_dmem_response_get, core_dmem_response_get, RDY_core_dmem_response_get, EN_fmc_imem_request_get, fmc_imem_request_get, RDY_fmc_imem_request_get, fmc_imem_response_put, EN_fmc_imem_response_put, RDY_fmc_imem_response_put, EN_fmc_dmem_request_get
, fmc_dmem_request_get, RDY_fmc_dmem_request_get, fmc_dmem_response_put, EN_fmc_dmem_response_put, RDY_fmc_dmem_response_put, EN_ram_imem_request_get, ram_imem_request_get, RDY_ram_imem_request_get, ram_imem_response_put, EN_ram_imem_response_put, RDY_ram_imem_response_put, EN_ram_dmem_request_get, ram_dmem_request_get, RDY_ram_dmem_request_get, ram_dmem_response_put, EN_ram_dmem_response_put, RDY_ram_dmem_response_put);
`ifdef USE_POWER_PINS
    inout vccd1;
    inout vssd1;
`endif
  reg \$auto$verilog_backend.cc:2083:dump_module$41  = 0;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:453.3-487.6" *)
  reg [100:0] _00_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:453.3-487.6" *)
  reg [100:0] _01_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:453.3-487.6" *)
  reg [32:0] _02_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:453.3-487.6" *)
  reg [32:0] _03_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:453.3-487.6" *)
  reg [32:0] _04_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:453.3-487.6" *)
  reg [32:0] _05_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:455.9-455.22" *)
  wire _06_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:291.7-291.65" *)
  wire _07_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:299.7-299.67" *)
  wire _08_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:345.7-346.48" *)
  wire _09_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:358.7-359.49" *)
  wire _10_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:383.7-384.63" *)
  wire _11_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:394.7-395.64" *)
  wire _12_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:291.7-291.34" *)
  wire _13_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:291.38-291.65" *)
  wire _14_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:299.7-299.35" *)
  wire _15_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:299.39-299.67" *)
  wire _16_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:310.38-310.62" *)
  wire _17_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:317.38-317.62" *)
  wire _18_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:324.38-324.62" *)
  wire _19_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:331.38-331.62" *)
  wire _20_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:359.7-359.49" *)
  wire _21_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:395.7-395.64" *)
  wire _22_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:369.7-369.59" *)
  wire _23_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:407.7-407.59" *)
  wire _24_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:447.7-447.50" *)
  wire _25_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:449.7-449.43" *)
  wire _26_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:350.7-352.31" *)
  wire [32:0] _27_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:354.7-356.43" *)
  wire [32:0] _28_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:361.7-363.31" *)
  wire [32:0] _29_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:365.7-367.43" *)
  wire [32:0] _30_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:371.7-373.54" *)
  wire [32:0] _31_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:375.7-377.28" *)
  wire [32:0] _32_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:379.7-381.40" *)
  wire [32:0] _33_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:386.7-388.31" *)
  wire [100:0] _34_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:390.7-392.43" *)
  wire [100:0] _35_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:399.7-401.31" *)
  wire [100:0] _36_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:403.7-405.43" *)
  wire [100:0] _37_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:409.7-411.54" *)
  wire [32:0] _38_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:413.7-415.28" *)
  wire [32:0] _39_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:417.7-419.40" *)
  wire [32:0] _40_;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:143.10-143.13" *)
  input CLK;
  wire CLK;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:158.10-158.34" *)
  input EN_core_dmem_request_put;
  wire EN_core_dmem_request_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:162.10-162.35" *)
  input EN_core_dmem_response_get;
  wire EN_core_dmem_response_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:148.10-148.34" *)
  input EN_core_imem_request_put;
  wire EN_core_imem_request_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:152.10-152.35" *)
  input EN_core_imem_response_get;
  wire EN_core_imem_response_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:177.10-177.33" *)
  input EN_fmc_dmem_request_get;
  wire EN_fmc_dmem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:183.10-183.34" *)
  input EN_fmc_dmem_response_put;
  wire EN_fmc_dmem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:167.10-167.33" *)
  input EN_fmc_imem_request_get;
  wire EN_fmc_imem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:173.10-173.34" *)
  input EN_fmc_imem_response_put;
  wire EN_fmc_imem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:197.10-197.33" *)
  input EN_ram_dmem_request_get;
  wire EN_ram_dmem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:203.10-203.34" *)
  input EN_ram_dmem_response_put;
  wire EN_ram_dmem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:187.10-187.33" *)
  input EN_ram_imem_request_get;
  wire EN_ram_imem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:193.10-193.34" *)
  input EN_ram_imem_response_put;
  wire EN_ram_imem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:280.17-280.62" *)
  wire [32:0] \MUX_forkDMem_fifoRes_rv$port0__write_1__VAL_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:281.3-281.48" *)
  wire [32:0] \MUX_forkDMem_fifoRes_rv$port0__write_1__VAL_2 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:282.3-282.48" *)
  wire [32:0] \MUX_forkIMem_fifoRes_rv$port0__write_1__VAL_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:283.3-283.48" *)
  wire [32:0] \MUX_forkIMem_fifoRes_rv$port0__write_1__VAL_2 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:159.10-159.35" *)
  output RDY_core_dmem_request_put;
  wire RDY_core_dmem_request_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:164.10-164.36" *)
  output RDY_core_dmem_response_get;
  wire RDY_core_dmem_response_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:149.10-149.35" *)
  output RDY_core_imem_request_put;
  wire RDY_core_imem_request_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:154.10-154.36" *)
  output RDY_core_imem_response_get;
  wire RDY_core_imem_response_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:179.10-179.34" *)
  output RDY_fmc_dmem_request_get;
  wire RDY_fmc_dmem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:184.10-184.35" *)
  output RDY_fmc_dmem_response_put;
  wire RDY_fmc_dmem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:169.10-169.34" *)
  output RDY_fmc_imem_request_get;
  wire RDY_fmc_imem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:174.10-174.35" *)
  output RDY_fmc_imem_response_put;
  wire RDY_fmc_imem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:199.10-199.34" *)
  output RDY_ram_dmem_request_get;
  wire RDY_ram_dmem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:204.10-204.35" *)
  output RDY_ram_dmem_response_put;
  wire RDY_ram_dmem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:189.10-189.34" *)
  output RDY_ram_imem_request_get;
  wire RDY_ram_imem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:194.10-194.35" *)
  output RDY_ram_imem_response_put;
  wire RDY_ram_imem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:144.10-144.15" *)
  input RST_N;
  wire RST_N;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:157.19-157.40" *)
  input [99:0] core_dmem_request_put;
  wire [99:0] core_dmem_request_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:286.8-286.64" *)
  wire core_dmem_request_put_BITS_99_TO_68_4_ULT_0x20_ETC___d15;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:163.19-163.41" *)
  output [31:0] core_dmem_response_get;
  wire [31:0] core_dmem_response_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:147.19-147.40" *)
  input [31:0] core_imem_request_put;
  wire [31:0] core_imem_request_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:287.8-287.49" *)
  wire core_imem_request_put_ULT_0x20000000___d1;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:153.19-153.41" *)
  output [31:0] core_imem_response_get;
  wire [31:0] core_imem_response_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:178.19-178.39" *)
  output [99:0] fmc_dmem_request_get;
  wire [99:0] fmc_dmem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:182.19-182.40" *)
  input [31:0] fmc_dmem_response_put;
  wire [31:0] fmc_dmem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:168.19-168.39" *)
  output [31:0] fmc_imem_request_get;
  wire [31:0] fmc_imem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:172.19-172.40" *)
  input [31:0] fmc_imem_response_put;
  wire [31:0] fmc_imem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:250.17-250.39" *)
  reg [100:0] forkDMem_fifoReqFMC_rv;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:251.18-251.45" *)
  wire [100:0] \forkDMem_fifoReqFMC_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:252.8-252.33" *)
  wire \forkDMem_fifoReqFMC_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:242.8-242.46" *)
  wire \forkDMem_fifoReqFMC_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:226.18-226.52" *)
  wire [100:0] \forkDMem_fifoReqFMC_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:227.4-227.38" *)
  wire [100:0] \forkDMem_fifoReqFMC_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:255.17-255.39" *)
  reg [100:0] forkDMem_fifoReqRAM_rv;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:256.18-256.45" *)
  wire [100:0] \forkDMem_fifoReqRAM_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:257.8-257.33" *)
  wire \forkDMem_fifoReqRAM_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:243.8-243.46" *)
  wire \forkDMem_fifoReqRAM_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:228.4-228.41" *)
  wire [100:0] \forkDMem_fifoReqRAM_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:229.4-229.38" *)
  wire [100:0] \forkDMem_fifoReqRAM_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:230.4-230.38" *)
  wire [100:0] \forkDMem_fifoReqRAM_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:260.16-260.35" *)
  reg [32:0] forkDMem_fifoRes_rv;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:261.17-261.41" *)
  wire [32:0] \forkDMem_fifoRes_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:262.8-262.30" *)
  wire \forkDMem_fifoRes_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:244.8-244.43" *)
  wire \forkDMem_fifoRes_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:231.17-231.51" *)
  wire [32:0] \forkDMem_fifoRes_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:232.3-232.34" *)
  wire [32:0] \forkDMem_fifoRes_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:233.3-233.34" *)
  wire [32:0] \forkDMem_fifoRes_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:265.16-265.38" *)
  reg [32:0] forkIMem_fifoReqFMC_rv;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:266.17-266.44" *)
  wire [32:0] \forkIMem_fifoReqFMC_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:267.8-267.33" *)
  wire \forkIMem_fifoReqFMC_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:245.8-245.46" *)
  wire \forkIMem_fifoReqFMC_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:234.3-234.40" *)
  wire [32:0] \forkIMem_fifoReqFMC_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:235.3-235.37" *)
  wire [32:0] \forkIMem_fifoReqFMC_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:236.3-236.37" *)
  wire [32:0] \forkIMem_fifoReqFMC_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:270.16-270.38" *)
  reg [32:0] forkIMem_fifoReqRAM_rv;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:271.17-271.44" *)
  wire [32:0] \forkIMem_fifoReqRAM_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:272.8-272.33" *)
  wire \forkIMem_fifoReqRAM_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:246.8-246.46" *)
  wire \forkIMem_fifoReqRAM_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:237.3-237.37" *)
  wire [32:0] \forkIMem_fifoReqRAM_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:238.3-238.37" *)
  wire [32:0] \forkIMem_fifoReqRAM_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:275.16-275.35" *)
  reg [32:0] forkIMem_fifoRes_rv;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:276.17-276.41" *)
  wire [32:0] \forkIMem_fifoRes_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:277.8-277.30" *)
  wire \forkIMem_fifoRes_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:247.8-247.43" *)
  wire \forkIMem_fifoRes_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:239.3-239.37" *)
  wire [32:0] \forkIMem_fifoRes_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:240.3-240.34" *)
  wire [32:0] \forkIMem_fifoRes_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:241.3-241.34" *)
  wire [32:0] \forkIMem_fifoRes_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:198.19-198.39" *)
  output [99:0] ram_dmem_request_get;
  wire [99:0] ram_dmem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:202.19-202.40" *)
  input [31:0] ram_dmem_response_put;
  wire [31:0] ram_dmem_response_put;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:188.19-188.39" *)
  output [31:0] ram_imem_request_get;
  wire [31:0] ram_imem_request_get;
  (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:192.19-192.40" *)
  input [31:0] ram_imem_response_put;
  wire [31:0] ram_imem_response_put;
  assign _06_ = RST_N == (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:455.9-455.22" *) 1'h0;
  assign _07_ = _13_ && (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:291.7-291.65" *) _14_;
  assign _08_ = _15_ && (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:299.7-299.67" *) _16_;
  assign _09_ = EN_core_imem_request_put && (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:345.7-346.48" *) core_imem_request_put_ULT_0x20000000___d1;
  assign _10_ = EN_core_imem_request_put && (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:358.7-359.49" *) _21_;
  assign _11_ = EN_core_dmem_request_put && (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:383.7-384.63" *) core_dmem_request_put_BITS_99_TO_68_4_ULT_0x20_ETC___d15;
  assign _12_ = EN_core_dmem_request_put && (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:394.7-395.64" *) _22_;
  assign _13_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:291.7-291.34" *) forkIMem_fifoReqFMC_rv[32];
  assign _14_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:291.38-291.65" *) forkIMem_fifoReqRAM_rv[32];
  assign _15_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:299.7-299.35" *) forkDMem_fifoReqFMC_rv[100];
  assign _16_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:299.39-299.67" *) forkDMem_fifoReqRAM_rv[100];
  assign _17_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:310.38-310.62" *) forkIMem_fifoRes_rv[32];
  assign _18_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:317.38-317.62" *) forkDMem_fifoRes_rv[32];
  assign _19_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:324.38-324.62" *) forkIMem_fifoRes_rv[32];
  assign _20_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:331.38-331.62" *) forkDMem_fifoRes_rv[32];
  assign _21_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:359.7-359.49" *) core_imem_request_put_ULT_0x20000000___d1;
  assign _22_ = ! (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:395.7-395.64" *) core_dmem_request_put_BITS_99_TO_68_4_ULT_0x20_ETC___d15;
  assign _23_ = EN_fmc_imem_response_put || (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:369.7-369.59" *) EN_ram_imem_response_put;
  assign _24_ = EN_fmc_dmem_response_put || (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:407.7-407.59" *) EN_ram_dmem_response_put;
  assign _25_ = core_dmem_request_put[99:68] < (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:447.7-447.50" *) 32'd536870912;
  assign _26_ = core_imem_request_put < (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:449.7-449.43" *) 32'd536870912;
  assign _27_ = \forkIMem_fifoReqFMC_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:350.7-352.31" *) \forkIMem_fifoReqFMC_rv$port0__write_1  : forkIMem_fifoReqFMC_rv;
  assign _28_ = EN_fmc_imem_request_get ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:354.7-356.43" *) 33'h0aaaaaaaa : \forkIMem_fifoReqFMC_rv$port1__read ;
  assign _29_ = \forkIMem_fifoReqRAM_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:361.7-363.31" *) \forkIMem_fifoReqFMC_rv$port0__write_1  : forkIMem_fifoReqRAM_rv;
  assign _30_ = EN_ram_imem_request_get ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:365.7-367.43" *) 33'h0aaaaaaaa : \forkIMem_fifoReqRAM_rv$port1__read ;
  assign _31_ = EN_fmc_imem_response_put ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:371.7-373.54" *) \MUX_forkIMem_fifoRes_rv$port0__write_1__VAL_1  : \MUX_forkIMem_fifoRes_rv$port0__write_1__VAL_2 ;
  assign _32_ = \forkIMem_fifoRes_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:375.7-377.28" *) \forkIMem_fifoRes_rv$port0__write_1  : forkIMem_fifoRes_rv;
  assign _33_ = EN_core_imem_response_get ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:379.7-381.40" *) 33'h0aaaaaaaa : \forkIMem_fifoRes_rv$port1__read ;
  assign _34_ = \forkDMem_fifoReqFMC_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:386.7-388.31" *) \forkDMem_fifoReqRAM_rv$port0__write_1  : forkDMem_fifoReqFMC_rv;
  assign _35_ = EN_fmc_dmem_request_get ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:390.7-392.43" *) 101'h0aaaaaaaaaaaaaaaaaaaaaaaaa : \forkDMem_fifoReqFMC_rv$port1__read ;
  assign _36_ = \forkDMem_fifoReqRAM_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:399.7-401.31" *) \forkDMem_fifoReqRAM_rv$port0__write_1  : forkDMem_fifoReqRAM_rv;
  assign _37_ = EN_ram_dmem_request_get ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:403.7-405.43" *) 101'h0aaaaaaaaaaaaaaaaaaaaaaaaa : \forkDMem_fifoReqRAM_rv$port1__read ;
  assign _38_ = EN_fmc_dmem_response_put ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:409.7-411.54" *) \MUX_forkDMem_fifoRes_rv$port0__write_1__VAL_1  : \MUX_forkDMem_fifoRes_rv$port0__write_1__VAL_2 ;
  assign _39_ = \forkDMem_fifoRes_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:413.7-415.28" *) \forkDMem_fifoRes_rv$port0__write_1  : forkDMem_fifoRes_rv;
  assign _40_ = EN_core_dmem_response_get ? (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:417.7-419.40" *) 33'h0aaaaaaaa : \forkDMem_fifoRes_rv$port1__read ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$41 ) begin end
    _00_ = forkDMem_fifoReqFMC_rv;
    _01_ = forkDMem_fifoReqRAM_rv;
    _02_ = forkDMem_fifoRes_rv;
    _03_ = forkIMem_fifoReqFMC_rv;
    _04_ = forkIMem_fifoReqRAM_rv;
    _05_ = forkIMem_fifoRes_rv;
    (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:455.5-486.10" *)
    casez (_06_)
      /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:455.9-455.22" */
      1'h1:
        begin
          _00_ = 101'h0aaaaaaaaaaaaaaaaaaaaaaaaa;
          _01_ = 101'h0aaaaaaaaaaaaaaaaaaaaaaaaa;
          _02_ = 33'h0aaaaaaaa;
          _03_ = 33'h0aaaaaaaa;
          _04_ = 33'h0aaaaaaaa;
          _05_ = 33'h0aaaaaaaa;
        end
      /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:466.5-466.9" */
      default:
        begin
          (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:468.9-470.36" *)
          casez (\forkDMem_fifoReqFMC_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:468.13-468.38" */
            1'h1:
                _00_ = \forkDMem_fifoReqFMC_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:471.2-473.36" *)
          casez (\forkDMem_fifoReqRAM_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:471.6-471.31" */
            1'h1:
                _01_ = \forkDMem_fifoReqRAM_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:474.2-476.33" *)
          casez (\forkDMem_fifoRes_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:474.6-474.28" */
            1'h1:
                _02_ = \forkDMem_fifoRes_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:477.2-479.36" *)
          casez (\forkIMem_fifoReqFMC_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:477.6-477.31" */
            1'h1:
                _03_ = \forkIMem_fifoReqFMC_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:480.2-482.36" *)
          casez (\forkIMem_fifoReqRAM_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:480.6-480.31" */
            1'h1:
                _04_ = \forkIMem_fifoReqRAM_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:483.2-485.33" *)
          casez (\forkIMem_fifoRes_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/lanai/frontend/LanaiFrontend/mkLanaiFrontend.v:483.6-483.28" */
            1'h1:
                _05_ = \forkIMem_fifoRes_rv$D_IN ;
            default:
                /* empty */;
          endcase
        end
    endcase
  end
  always @(posedge CLK) begin
      forkDMem_fifoReqFMC_rv <= _00_;
      forkDMem_fifoReqRAM_rv <= _01_;
      forkDMem_fifoRes_rv <= _02_;
      forkIMem_fifoReqFMC_rv <= _03_;
      forkIMem_fifoReqRAM_rv <= _04_;
      forkIMem_fifoRes_rv <= _05_;
  end
  assign RDY_core_imem_request_put = _07_;
  assign core_imem_response_get = \forkIMem_fifoRes_rv$port1__read [31:0];
  assign RDY_core_imem_response_get = \forkIMem_fifoRes_rv$port1__read [32];
  assign RDY_core_dmem_request_put = _08_;
  assign core_dmem_response_get = \forkDMem_fifoRes_rv$port1__read [31:0];
  assign RDY_core_dmem_response_get = \forkDMem_fifoRes_rv$port1__read [32];
  assign fmc_imem_request_get = \forkIMem_fifoReqFMC_rv$port1__read [31:0];
  assign RDY_fmc_imem_request_get = \forkIMem_fifoReqFMC_rv$port1__read [32];
  assign RDY_fmc_imem_response_put = _17_;
  assign fmc_dmem_request_get = \forkDMem_fifoReqFMC_rv$port1__read [99:0];
  assign RDY_fmc_dmem_request_get = \forkDMem_fifoReqFMC_rv$port1__read [100];
  assign RDY_fmc_dmem_response_put = _18_;
  assign ram_imem_request_get = \forkIMem_fifoReqRAM_rv$port1__read [31:0];
  assign RDY_ram_imem_request_get = \forkIMem_fifoReqRAM_rv$port1__read [32];
  assign RDY_ram_imem_response_put = _19_;
  assign ram_dmem_request_get = \forkDMem_fifoReqRAM_rv$port1__read [99:0];
  assign RDY_ram_dmem_request_get = \forkDMem_fifoReqRAM_rv$port1__read [100];
  assign RDY_ram_dmem_response_put = _20_;
  assign \MUX_forkDMem_fifoRes_rv$port0__write_1__VAL_1  = { 1'h1, fmc_dmem_response_put };
  assign \MUX_forkDMem_fifoRes_rv$port0__write_1__VAL_2  = { 1'h1, ram_dmem_response_put };
  assign \MUX_forkIMem_fifoRes_rv$port0__write_1__VAL_1  = { 1'h1, fmc_imem_response_put };
  assign \MUX_forkIMem_fifoRes_rv$port0__write_1__VAL_2  = { 1'h1, ram_imem_response_put };
  assign \forkIMem_fifoReqFMC_rv$EN_port0__write  = _09_;
  assign \forkIMem_fifoReqFMC_rv$port0__write_1  = { 1'h1, core_imem_request_put };
  assign \forkIMem_fifoReqFMC_rv$port1__read  = _27_;
  assign \forkIMem_fifoReqFMC_rv$port2__read  = _28_;
  assign \forkIMem_fifoReqRAM_rv$EN_port0__write  = _10_;
  assign \forkIMem_fifoReqRAM_rv$port1__read  = _29_;
  assign \forkIMem_fifoReqRAM_rv$port2__read  = _30_;
  assign \forkIMem_fifoRes_rv$EN_port0__write  = _23_;
  assign \forkIMem_fifoRes_rv$port0__write_1  = _31_;
  assign \forkIMem_fifoRes_rv$port1__read  = _32_;
  assign \forkIMem_fifoRes_rv$port2__read  = _33_;
  assign \forkDMem_fifoReqFMC_rv$EN_port0__write  = _11_;
  assign \forkDMem_fifoReqFMC_rv$port1__read  = _34_;
  assign \forkDMem_fifoReqFMC_rv$port2__read  = _35_;
  assign \forkDMem_fifoReqRAM_rv$EN_port0__write  = _12_;
  assign \forkDMem_fifoReqRAM_rv$port0__write_1  = { 1'h1, core_dmem_request_put };
  assign \forkDMem_fifoReqRAM_rv$port1__read  = _36_;
  assign \forkDMem_fifoReqRAM_rv$port2__read  = _37_;
  assign \forkDMem_fifoRes_rv$EN_port0__write  = _24_;
  assign \forkDMem_fifoRes_rv$port0__write_1  = _38_;
  assign \forkDMem_fifoRes_rv$port1__read  = _39_;
  assign \forkDMem_fifoRes_rv$port2__read  = _40_;
  assign \forkDMem_fifoReqFMC_rv$D_IN  = \forkDMem_fifoReqFMC_rv$port2__read ;
  assign \forkDMem_fifoReqFMC_rv$EN  = 1'h1;
  assign \forkDMem_fifoReqRAM_rv$D_IN  = \forkDMem_fifoReqRAM_rv$port2__read ;
  assign \forkDMem_fifoReqRAM_rv$EN  = 1'h1;
  assign \forkDMem_fifoRes_rv$D_IN  = \forkDMem_fifoRes_rv$port2__read ;
  assign \forkDMem_fifoRes_rv$EN  = 1'h1;
  assign \forkIMem_fifoReqFMC_rv$D_IN  = \forkIMem_fifoReqFMC_rv$port2__read ;
  assign \forkIMem_fifoReqFMC_rv$EN  = 1'h1;
  assign \forkIMem_fifoReqRAM_rv$D_IN  = \forkIMem_fifoReqRAM_rv$port2__read ;
  assign \forkIMem_fifoReqRAM_rv$EN  = 1'h1;
  assign \forkIMem_fifoRes_rv$D_IN  = \forkIMem_fifoRes_rv$port2__read ;
  assign \forkIMem_fifoRes_rv$EN  = 1'h1;
  assign core_dmem_request_put_BITS_99_TO_68_4_ULT_0x20_ETC___d15 = _25_;
  assign core_imem_request_put_ULT_0x20000000___d1 = _26_;
endmodule

