/* Generated by Yosys 0.15 (git sha1 yosys-0.15, gcc 10.3.0 -fPIC -Os) */

(* hdlname = "\\mkQF100Fabric" *)
(* top =  1  *)
(* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:105.1-646.10" *)
module mkQF100Fabric(
`ifdef USE_POWER_PINS
    VPWR,
    VGND,
`endif
    CLK, RST_N, cpu_cyc_i, cpu_stb_i, cpu_adr_i, cpu_dat_i, cpu_sel_i, cpu_we_i, cpu_ack_o, cpu_err_o, cpu_rty_o, cpu_dat_o, spi_cyc_o, spi_stb_o, spi_adr_o, spi_dat_o, spi_sel_o, spi_we_o, spi_ack_i, spi_err_i, spi_rty_i
, spi_dat_i);
`ifdef USE_POWER_PINS
    inout VPWR;
    inout VGND;
`endif
  reg \$auto$verilog_backend.cc:2083:dump_module$116  = 0;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg [69:0] _000_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg [33:0] _001_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg _002_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg [69:0] _003_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg [33:0] _004_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg _005_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:559.3-601.6" *)
  reg [69:0] _006_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:444.7-444.67" *)
  wire _007_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:495.7-495.67" *)
  wire _008_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:504.7-504.67" *)
  wire _009_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:561.9-561.22" *)
  wire _010_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:289.7-290.58" *)
  wire _011_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:309.7-310.54" *)
  wire _012_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:314.7-315.54" *)
  wire _013_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:342.7-343.54" *)
  wire _014_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:342.7-344.54" *)
  wire _015_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:348.7-349.67" *)
  wire _016_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:353.7-354.48" *)
  wire _017_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:353.7-355.76" *)
  wire _018_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:359.7-360.54" *)
  wire _019_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:359.7-361.49" *)
  wire _020_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:365.7-366.58" *)
  wire _021_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:393.7-393.29" *)
  wire _022_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.8-404.31" *)
  wire _023_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.8-404.45" *)
  wire _024_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:416.7-417.40" *)
  wire _025_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:423.7-424.60" *)
  wire _026_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:423.7-425.53" *)
  wire _027_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:441.7-442.49" *)
  wire _028_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:441.7-443.37" *)
  wire _029_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:441.7-444.67" *)
  wire _030_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:452.7-453.49" *)
  wire _031_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:452.7-454.50" *)
  wire _032_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:452.7-455.54" *)
  wire _033_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:461.7-462.49" *)
  wire _034_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:461.7-463.50" *)
  wire _035_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:461.7-464.54" *)
  wire _036_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:474.7-475.60" *)
  wire _037_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:474.7-476.53" *)
  wire _038_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:482.7-483.40" *)
  wire _039_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:492.7-493.49" *)
  wire _040_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:492.7-494.37" *)
  wire _041_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:492.7-495.67" *)
  wire _042_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:501.7-502.49" *)
  wire _043_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:501.7-503.37" *)
  wire _044_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:501.7-504.67" *)
  wire _045_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:509.7-510.60" *)
  wire _046_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:509.7-511.53" *)
  wire _047_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:513.7-514.48" *)
  wire _048_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:543.7-544.76" *)
  wire _049_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:548.7-549.54" *)
  wire _050_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:548.7-550.49" *)
  wire _051_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:300.8-300.56" *)
  wire _052_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:301.8-301.60" *)
  wire _053_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:319.8-319.62" *)
  wire _054_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:320.8-320.56" *)
  wire _055_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:326.8-326.62" *)
  wire _056_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:327.8-327.56" *)
  wire _057_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:335.8-335.62" *)
  wire _058_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:336.8-336.56" *)
  wire _059_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:355.7-355.76" *)
  wire _060_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:359.7-359.53" *)
  wire _061_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:361.7-361.49" *)
  wire _062_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:375.8-375.56" *)
  wire _063_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:376.8-376.60" *)
  wire _064_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.21-404.31" *)
  wire _065_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.35-404.45" *)
  wire _066_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:417.7-417.40" *)
  wire _067_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:425.7-425.53" *)
  wire _068_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:442.7-442.49" *)
  wire _069_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:443.7-443.37" *)
  wire _070_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:453.7-453.49" *)
  wire _071_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:462.7-462.49" *)
  wire _072_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:467.9-467.63" *)
  wire _073_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:476.7-476.53" *)
  wire _074_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:483.7-483.40" *)
  wire _075_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:493.7-493.49" *)
  wire _076_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:494.7-494.37" *)
  wire _077_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:502.7-502.49" *)
  wire _078_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:503.7-503.37" *)
  wire _079_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:511.7-511.53" *)
  wire _080_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:513.7-513.53" *)
  wire _081_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:543.7-543.71" *)
  wire _082_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:544.7-544.76" *)
  wire _083_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:548.7-548.53" *)
  wire _084_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:550.7-550.49" *)
  wire _085_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:300.8-301.60" *)
  wire _086_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:319.8-320.56" *)
  wire _087_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:326.8-327.56" *)
  wire _088_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:335.8-336.56" *)
  wire _089_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:375.8-376.60" *)
  wire _090_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:398.7-399.75" *)
  wire _091_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:408.7-408.29" *)
  wire _092_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:408.7-408.42" *)
  wire _093_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:434.7-435.75" *)
  wire _094_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:506.7-507.36" *)
  wire _095_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:546.7-547.75" *)
  wire _096_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:546.7-550.49" *)
  wire _097_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:300.7-305.11" *)
  wire [31:0] _098_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:303.10-305.10" *)
  wire [31:0] _099_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:319.7-322.59" *)
  wire [31:0] _100_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:326.7-331.11" *)
  wire [31:0] _101_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:329.10-331.10" *)
  wire [31:0] _102_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:335.7-338.57" *)
  wire [3:0] _103_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:375.7-380.11" *)
  wire [31:0] _104_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:378.10-380.10" *)
  wire [31:0] _105_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.7-406.22" *)
  wire [32:0] _106_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:412.7-414.50" *)
  wire [69:0] _107_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:419.7-421.62" *)
  wire [69:0] _108_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:430.7-432.50" *)
  wire [33:0] _109_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:437.7-439.62" *)
  wire [33:0] _110_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:448.7-450.46" *)
  wire [69:0] _111_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:457.7-459.58" *)
  wire [69:0] _112_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:470.7-472.46" *)
  wire [33:0] _113_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:478.7-480.58" *)
  wire [33:0] _114_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:488.7-490.37" *)
  wire [69:0] _115_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:497.7-499.49" *)
  wire [69:0] _116_;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:139.10-139.13" *)
  input CLK;
  wire CLK;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:285.8-285.68" *)
  wire \MUX_fabric_upstreamConnectors_0_inner_pending$write_1__SEL_3 ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:140.10-140.15" *)
  input RST_N;
  wire RST_N;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:281.8-281.71" *)
  wire WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:282.8-282.76" *)
  wire WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:151.10-151.19" *)
  output cpu_ack_o;
  wire cpu_ack_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:145.19-145.28" *)
  input [31:0] cpu_adr_i;
  wire [31:0] cpu_adr_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:143.10-143.19" *)
  input cpu_cyc_i;
  wire cpu_cyc_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:146.19-146.28" *)
  input [31:0] cpu_dat_i;
  wire [31:0] cpu_dat_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:160.19-160.28" *)
  output [31:0] cpu_dat_o;
  wire [31:0] cpu_dat_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:154.10-154.19" *)
  output cpu_err_o;
  wire cpu_err_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:157.10-157.19" *)
  output cpu_rty_o;
  wire cpu_rty_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:147.18-147.27" *)
  input [3:0] cpu_sel_i;
  wire [3:0] cpu_sel_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:144.10-144.19" *)
  input cpu_stb_i;
  wire cpu_stb_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:148.10-148.18" *)
  input cpu_we_i;
  wire cpu_we_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:247.16-247.53" *)
  reg [69:0] fabric_downstreamConnectors_0_fReq_rv;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:248.17-248.59" *)
  wire [69:0] \fabric_downstreamConnectors_0_fReq_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:249.8-249.48" *)
  wire \fabric_downstreamConnectors_0_fReq_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:229.8-229.61" *)
  wire \fabric_downstreamConnectors_0_fReq_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:230.8-230.61" *)
  wire \fabric_downstreamConnectors_0_fReq_rv$EN_port1__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:210.17-210.69" *)
  wire [69:0] \fabric_downstreamConnectors_0_fReq_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:211.3-211.52" *)
  wire [69:0] \fabric_downstreamConnectors_0_fReq_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:212.3-212.52" *)
  wire [69:0] \fabric_downstreamConnectors_0_fReq_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:252.16-252.53" *)
  reg [33:0] fabric_downstreamConnectors_0_fRes_rv;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:253.17-253.59" *)
  wire [33:0] \fabric_downstreamConnectors_0_fRes_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:254.8-254.48" *)
  wire \fabric_downstreamConnectors_0_fRes_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:231.8-231.61" *)
  wire \fabric_downstreamConnectors_0_fRes_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:232.8-232.61" *)
  wire \fabric_downstreamConnectors_0_fRes_rv$EN_port1__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:221.17-221.69" *)
  wire [33:0] \fabric_downstreamConnectors_0_fRes_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:222.3-222.52" *)
  wire [33:0] \fabric_downstreamConnectors_0_fRes_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:223.3-223.52" *)
  wire [33:0] \fabric_downstreamConnectors_0_fRes_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:228.17-228.60" *)
  wire [32:0] \fabric_downstreamConnectors_0_incoming$wget ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:233.8-233.51" *)
  wire \fabric_downstreamConnectors_0_incoming$whas ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:213.3-213.46" *)
  wire [69:0] \fabric_downstreamConnectors_0_outgoing$wget ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:257.7-257.36" *)
  reg fabric_downstreamPending_0_rv;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:258.8-258.42" *)
  wire \fabric_downstreamPending_0_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:258.44-258.76" *)
  wire \fabric_downstreamPending_0_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:234.8-234.53" *)
  wire \fabric_downstreamPending_0_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:235.8-235.53" *)
  wire \fabric_downstreamPending_0_rv$EN_port1__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:236.8-236.49" *)
  wire \fabric_downstreamPending_0_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:237.8-237.49" *)
  wire \fabric_downstreamPending_0_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:261.16-261.57" *)
  reg [69:0] fabric_upstreamConnectors_0_inner_fReq_rv;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:262.17-262.63" *)
  wire [69:0] \fabric_upstreamConnectors_0_inner_fReq_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:263.8-263.52" *)
  wire \fabric_upstreamConnectors_0_inner_fReq_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:238.8-238.65" *)
  wire \fabric_upstreamConnectors_0_inner_fReq_rv$EN_port1__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:214.3-214.59" *)
  wire [69:0] \fabric_upstreamConnectors_0_inner_fReq_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:215.3-215.56" *)
  wire [69:0] \fabric_upstreamConnectors_0_inner_fReq_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:216.3-216.56" *)
  wire [69:0] \fabric_upstreamConnectors_0_inner_fReq_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:266.16-266.57" *)
  reg [33:0] fabric_upstreamConnectors_0_inner_fRes_rv;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:267.17-267.63" *)
  wire [33:0] \fabric_upstreamConnectors_0_inner_fRes_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:268.8-268.52" *)
  wire \fabric_upstreamConnectors_0_inner_fRes_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:239.8-239.65" *)
  wire \fabric_upstreamConnectors_0_inner_fRes_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:240.8-240.65" *)
  wire \fabric_upstreamConnectors_0_inner_fRes_rv$EN_port1__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:224.3-224.59" *)
  wire [33:0] \fabric_upstreamConnectors_0_inner_fRes_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:225.3-225.56" *)
  wire [33:0] \fabric_upstreamConnectors_0_inner_fRes_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:226.3-226.56" *)
  wire [33:0] \fabric_upstreamConnectors_0_inner_fRes_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:220.17-220.64" *)
  wire [68:0] \fabric_upstreamConnectors_0_inner_incoming$wget ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:241.8-241.55" *)
  wire \fabric_upstreamConnectors_0_inner_incoming$whas ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:227.3-227.50" *)
  wire [33:0] \fabric_upstreamConnectors_0_inner_outgoing$wget ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:242.8-242.55" *)
  wire \fabric_upstreamConnectors_0_inner_outgoing$whas ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:271.7-271.48" *)
  reg fabric_upstreamConnectors_0_inner_pending;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:272.8-272.54" *)
  wire \fabric_upstreamConnectors_0_inner_pending$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:273.8-273.52" *)
  wire \fabric_upstreamConnectors_0_inner_pending$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:196.8-196.56" *)
  wire \fabric_upstreamConnectors_0_inner_probeAck$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:197.8-197.62" *)
  wire \fabric_upstreamConnectors_0_inner_probeAck$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:192.17-192.65" *)
  wire [31:0] \fabric_upstreamConnectors_0_inner_probeAdr$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:198.8-198.62" *)
  wire \fabric_upstreamConnectors_0_inner_probeAdr$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:199.8-199.56" *)
  wire \fabric_upstreamConnectors_0_inner_probeCyc$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:200.8-200.62" *)
  wire \fabric_upstreamConnectors_0_inner_probeCyc$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:193.3-193.54" *)
  wire [31:0] \fabric_upstreamConnectors_0_inner_probeDataIn$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:201.8-201.65" *)
  wire \fabric_upstreamConnectors_0_inner_probeDataIn$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:194.3-194.55" *)
  wire [31:0] \fabric_upstreamConnectors_0_inner_probeDataOut$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:202.8-202.66" *)
  wire \fabric_upstreamConnectors_0_inner_probeDataOut$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:195.16-195.64" *)
  wire [3:0] \fabric_upstreamConnectors_0_inner_probeSel$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:203.8-203.62" *)
  wire \fabric_upstreamConnectors_0_inner_probeSel$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:204.8-204.56" *)
  wire \fabric_upstreamConnectors_0_inner_probeStb$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:205.8-205.62" *)
  wire \fabric_upstreamConnectors_0_inner_probeStb$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:206.8-206.55" *)
  wire \fabric_upstreamConnectors_0_inner_probeWe$PROBE ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:207.8-207.61" *)
  wire \fabric_upstreamConnectors_0_inner_probeWe$PROBE_VALID ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:276.16-276.44" *)
  reg [69:0] fabric_upstreamRequests_0_rv;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:277.17-277.50" *)
  wire [69:0] \fabric_upstreamRequests_0_rv$D_IN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:278.8-278.39" *)
  wire \fabric_upstreamRequests_0_rv$EN ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:243.8-243.52" *)
  wire \fabric_upstreamRequests_0_rv$EN_port0__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:244.8-244.52" *)
  wire \fabric_upstreamRequests_0_rv$EN_port1__write ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:217.3-217.46" *)
  wire [69:0] \fabric_upstreamRequests_0_rv$port0__write_1 ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:218.3-218.43" *)
  wire [69:0] \fabric_upstreamRequests_0_rv$port1__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:219.3-219.43" *)
  wire [69:0] \fabric_upstreamRequests_0_rv$port2__read ;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:181.10-181.19" *)
  input spi_ack_i;
  wire spi_ack_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:169.19-169.28" *)
  output [31:0] spi_adr_o;
  wire [31:0] spi_adr_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:163.10-163.19" *)
  output spi_cyc_o;
  wire spi_cyc_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:184.19-184.28" *)
  input [31:0] spi_dat_i;
  wire [31:0] spi_dat_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:172.19-172.28" *)
  output [31:0] spi_dat_o;
  wire [31:0] spi_dat_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:182.10-182.19" *)
  input spi_err_i;
  wire spi_err_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:183.10-183.19" *)
  input spi_rty_i;
  wire spi_rty_i;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:175.18-175.27" *)
  output [3:0] spi_sel_o;
  wire [3:0] spi_sel_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:166.10-166.19" *)
  output spi_stb_o;
  wire spi_stb_o;
  (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:178.10-178.18" *)
  output spi_we_o;
  wire spi_we_o;
  assign _007_ = \fabric_upstreamRequests_0_rv$port1__read [68:49] == (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:444.7-444.67" *) 20'h40013;
  assign _008_ = \fabric_upstreamRequests_0_rv$port1__read [68:49] == (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:495.7-495.67" *) 20'h40013;
  assign _009_ = \fabric_upstreamRequests_0_rv$port1__read [68:49] == (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:504.7-504.67" *) 20'h40013;
  assign _010_ = RST_N == (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:561.9-561.22" *) 1'h0;
  assign _011_ = \fabric_upstreamConnectors_0_inner_outgoing$whas  && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:289.7-290.58" *) \fabric_upstreamConnectors_0_inner_outgoing$wget [33];
  assign _012_ = \fabric_downstreamConnectors_0_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:309.7-310.54" *) \fabric_downstreamConnectors_0_outgoing$wget [69];
  assign _013_ = \fabric_downstreamConnectors_0_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:314.7-315.54" *) \fabric_downstreamConnectors_0_outgoing$wget [69];
  assign _014_ = \fabric_downstreamConnectors_0_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:342.7-343.54" *) \fabric_downstreamConnectors_0_outgoing$wget [69];
  assign _015_ = _014_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:342.7-344.54" *) \fabric_downstreamConnectors_0_outgoing$wget [36];
  assign _016_ = \fabric_upstreamConnectors_0_inner_fRes_rv$port1__read [33] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:348.7-349.67" *) \MUX_fabric_upstreamConnectors_0_inner_pending$write_1__SEL_3 ;
  assign _017_ = \fabric_upstreamConnectors_0_inner_fRes_rv$port1__read [33] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:353.7-354.48" *) fabric_upstreamConnectors_0_inner_pending;
  assign _018_ = _017_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:353.7-355.76" *) _060_;
  assign _019_ = _061_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:359.7-360.54" *) \fabric_upstreamConnectors_0_inner_incoming$whas ;
  assign _020_ = _019_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:359.7-361.49" *) _062_;
  assign _021_ = \fabric_upstreamConnectors_0_inner_outgoing$whas  && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:365.7-366.58" *) \fabric_upstreamConnectors_0_inner_outgoing$wget [33];
  assign _022_ = cpu_cyc_i && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:393.7-393.29" *) cpu_stb_i;
  assign _023_ = spi_ack_i && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.8-404.31" *) _065_;
  assign _024_ = _023_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.8-404.45" *) _066_;
  assign _025_ = \fabric_upstreamConnectors_0_inner_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:416.7-417.40" *) _067_;
  assign _026_ = \fabric_downstreamPending_0_rv$port1__read  && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:423.7-424.60" *) \fabric_downstreamConnectors_0_fRes_rv$port1__read [33];
  assign _027_ = _026_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:423.7-425.53" *) _068_;
  assign _028_ = \fabric_upstreamRequests_0_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:441.7-442.49" *) _069_;
  assign _029_ = _028_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:441.7-443.37" *) _070_;
  assign _030_ = _029_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:441.7-444.67" *) _007_;
  assign _031_ = \fabric_downstreamConnectors_0_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:452.7-453.49" *) _071_;
  assign _032_ = _031_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:452.7-454.50" *) \fabric_downstreamConnectors_0_incoming$whas ;
  assign _033_ = _032_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:452.7-455.54" *) \fabric_downstreamConnectors_0_incoming$wget [32];
  assign _034_ = \fabric_downstreamConnectors_0_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:461.7-462.49" *) _072_;
  assign _035_ = _034_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:461.7-463.50" *) \fabric_downstreamConnectors_0_incoming$whas ;
  assign _036_ = _035_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:461.7-464.54" *) \fabric_downstreamConnectors_0_incoming$wget [32];
  assign _037_ = \fabric_downstreamPending_0_rv$port1__read  && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:474.7-475.60" *) \fabric_downstreamConnectors_0_fRes_rv$port1__read [33];
  assign _038_ = _037_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:474.7-476.53" *) _074_;
  assign _039_ = \fabric_upstreamConnectors_0_inner_fReq_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:482.7-483.40" *) _075_;
  assign _040_ = \fabric_upstreamRequests_0_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:492.7-493.49" *) _076_;
  assign _041_ = _040_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:492.7-494.37" *) _077_;
  assign _042_ = _041_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:492.7-495.67" *) _008_;
  assign _043_ = \fabric_upstreamRequests_0_rv$port1__read [69] && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:501.7-502.49" *) _078_;
  assign _044_ = _043_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:501.7-503.37" *) _079_;
  assign _045_ = _044_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:501.7-504.67" *) _009_;
  assign _046_ = \fabric_downstreamPending_0_rv$port1__read  && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:509.7-510.60" *) \fabric_downstreamConnectors_0_fRes_rv$port1__read [33];
  assign _047_ = _046_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:509.7-511.53" *) _080_;
  assign _048_ = _081_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:513.7-514.48" *) \fabric_downstreamPending_0_rv$port1__read ;
  assign _049_ = _082_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:543.7-544.76" *) _083_;
  assign _050_ = _084_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:548.7-549.54" *) \fabric_upstreamConnectors_0_inner_incoming$whas ;
  assign _051_ = _050_ && (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:548.7-550.49" *) _085_;
  assign _052_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:300.8-300.56" *) \fabric_upstreamConnectors_0_inner_outgoing$whas ;
  assign _053_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:301.8-301.60" *) \fabric_upstreamConnectors_0_inner_outgoing$wget [33];
  assign _054_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:319.8-319.62" *) \fabric_downstreamConnectors_0_fReq_rv$port1__read [69];
  assign _055_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:320.8-320.56" *) \fabric_downstreamConnectors_0_outgoing$wget [69];
  assign _056_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:326.8-326.62" *) \fabric_downstreamConnectors_0_fReq_rv$port1__read [69];
  assign _057_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:327.8-327.56" *) \fabric_downstreamConnectors_0_outgoing$wget [69];
  assign _058_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:335.8-335.62" *) \fabric_downstreamConnectors_0_fReq_rv$port1__read [69];
  assign _059_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:336.8-336.56" *) \fabric_downstreamConnectors_0_outgoing$wget [69];
  assign _060_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:355.7-355.76" *) WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast;
  assign _061_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:359.7-359.53" *) fabric_upstreamConnectors_0_inner_fReq_rv[69];
  assign _062_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:361.7-361.49" *) fabric_upstreamConnectors_0_inner_pending;
  assign _063_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:375.8-375.56" *) \fabric_upstreamConnectors_0_inner_outgoing$whas ;
  assign _064_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:376.8-376.60" *) \fabric_upstreamConnectors_0_inner_outgoing$wget [33];
  assign _065_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.21-404.31" *) spi_err_i;
  assign _066_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.35-404.45" *) spi_rty_i;
  assign _067_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:417.7-417.40" *) fabric_upstreamRequests_0_rv[69];
  assign _068_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:425.7-425.53" *) fabric_upstreamConnectors_0_inner_fRes_rv[33];
  assign _069_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:442.7-442.49" *) fabric_downstreamConnectors_0_fReq_rv[69];
  assign _070_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:443.7-443.37" *) fabric_downstreamPending_0_rv;
  assign _071_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:453.7-453.49" *) fabric_downstreamConnectors_0_fRes_rv[33];
  assign _072_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:462.7-462.49" *) fabric_downstreamConnectors_0_fRes_rv[33];
  assign _073_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:467.9-467.63" *) \fabric_downstreamConnectors_0_fReq_rv$port1__read [36];
  assign _074_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:476.7-476.53" *) fabric_upstreamConnectors_0_inner_fRes_rv[33];
  assign _075_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:483.7-483.40" *) fabric_upstreamRequests_0_rv[69];
  assign _076_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:493.7-493.49" *) fabric_downstreamConnectors_0_fReq_rv[69];
  assign _077_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:494.7-494.37" *) fabric_downstreamPending_0_rv;
  assign _078_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:502.7-502.49" *) fabric_downstreamConnectors_0_fReq_rv[69];
  assign _079_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:503.7-503.37" *) fabric_downstreamPending_0_rv;
  assign _080_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:511.7-511.53" *) fabric_upstreamConnectors_0_inner_fRes_rv[33];
  assign _081_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:513.7-513.53" *) \fabric_downstreamPending_0_rv$EN_port1__write ;
  assign _082_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:543.7-543.71" *) WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing;
  assign _083_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:544.7-544.76" *) WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast;
  assign _084_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:548.7-548.53" *) fabric_upstreamConnectors_0_inner_fReq_rv[69];
  assign _085_ = ! (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:550.7-550.49" *) fabric_upstreamConnectors_0_inner_pending;
  assign _086_ = _052_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:300.8-301.60" *) _053_;
  assign _087_ = _054_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:319.8-320.56" *) _055_;
  assign _088_ = _056_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:326.8-327.56" *) _057_;
  assign _089_ = _058_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:335.8-336.56" *) _059_;
  assign _090_ = _063_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:375.8-376.60" *) _064_;
  assign _091_ = WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:398.7-399.75" *) WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast;
  assign _092_ = spi_ack_i || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:408.7-408.29" *) spi_err_i;
  assign _093_ = _092_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:408.7-408.42" *) spi_rty_i;
  assign _094_ = WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:434.7-435.75" *) WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast;
  assign _095_ = \fabric_downstreamPending_0_rv$EN_port0__write  || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:506.7-507.36" *) fabric_downstreamPending_0_rv;
  assign _096_ = WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:546.7-547.75" *) WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast;
  assign _097_ = _096_ || (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:546.7-550.49" *) _051_;
  assign _098_ = _086_ ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:300.7-305.11" *) 32'd0 : _099_;
  assign _099_ = \fabric_upstreamConnectors_0_inner_outgoing$wget [32] ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:303.10-305.10" *) \fabric_upstreamConnectors_0_inner_outgoing$wget [31:0] : 32'd0;
  assign _100_ = _087_ ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:319.7-322.59" *) 32'd0 : \fabric_downstreamConnectors_0_outgoing$wget [68:37];
  assign _101_ = _088_ ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:326.7-331.11" *) 32'd0 : _102_;
  assign _102_ = \fabric_downstreamConnectors_0_outgoing$wget [36] ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:329.10-331.10" *) \fabric_downstreamConnectors_0_outgoing$wget [35:4] : 32'd0;
  assign _103_ = _089_ ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:335.7-338.57" *) 4'h0 : \fabric_downstreamConnectors_0_outgoing$wget [3:0];
  assign _104_ = _090_ ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:375.7-380.11" *) 32'd0 : _105_;
  assign _105_ = \fabric_upstreamConnectors_0_inner_outgoing$wget [32] ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:378.10-380.10" *) \fabric_upstreamConnectors_0_inner_outgoing$wget [31:0] : 32'd0;
  assign _106_ = _024_ ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:404.7-406.22" *) { 1'h1, spi_dat_i } : 33'h100000000;
  assign _107_ = \MUX_fabric_upstreamConnectors_0_inner_pending$write_1__SEL_3  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:412.7-414.50" *) \fabric_upstreamConnectors_0_inner_fReq_rv$port0__write_1  : fabric_upstreamConnectors_0_inner_fReq_rv;
  assign _108_ = \fabric_upstreamConnectors_0_inner_fReq_rv$EN_port1__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:419.7-421.62" *) 70'h0aaaaaaaaaaaaaaaaa : \fabric_upstreamConnectors_0_inner_fReq_rv$port1__read ;
  assign _109_ = \fabric_upstreamConnectors_0_inner_fRes_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:430.7-432.50" *) \fabric_upstreamConnectors_0_inner_fRes_rv$port0__write_1  : fabric_upstreamConnectors_0_inner_fRes_rv;
  assign _110_ = \fabric_upstreamConnectors_0_inner_fRes_rv$EN_port1__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:437.7-439.62" *) 34'h0aaaaaaaa : \fabric_upstreamConnectors_0_inner_fRes_rv$port1__read ;
  assign _111_ = \fabric_downstreamConnectors_0_fReq_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:448.7-450.46" *) \fabric_downstreamConnectors_0_fReq_rv$port0__write_1  : fabric_downstreamConnectors_0_fReq_rv;
  assign _112_ = \fabric_downstreamConnectors_0_fReq_rv$EN_port1__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:457.7-459.58" *) 70'h0aaaaaaaaaaaaaaaaa : \fabric_downstreamConnectors_0_fReq_rv$port1__read ;
  assign _113_ = \fabric_downstreamConnectors_0_fRes_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:470.7-472.46" *) \fabric_downstreamConnectors_0_fRes_rv$port0__write_1  : fabric_downstreamConnectors_0_fRes_rv;
  assign _114_ = \fabric_downstreamConnectors_0_fRes_rv$EN_port1__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:478.7-480.58" *) 34'h0aaaaaaaa : \fabric_downstreamConnectors_0_fRes_rv$port1__read ;
  assign _115_ = \fabric_upstreamRequests_0_rv$EN_port0__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:488.7-490.37" *) \fabric_upstreamRequests_0_rv$port0__write_1  : fabric_upstreamRequests_0_rv;
  assign _116_ = \fabric_upstreamRequests_0_rv$EN_port1__write  ? (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:497.7-499.49" *) 70'h0aaaaaaaaaaaaaaaaa : \fabric_upstreamRequests_0_rv$port1__read ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$116 ) begin end
    _000_ = fabric_downstreamConnectors_0_fReq_rv;
    _001_ = fabric_downstreamConnectors_0_fRes_rv;
    _002_ = fabric_downstreamPending_0_rv;
    _003_ = fabric_upstreamConnectors_0_inner_fReq_rv;
    _004_ = fabric_upstreamConnectors_0_inner_fRes_rv;
    _005_ = fabric_upstreamConnectors_0_inner_pending;
    _006_ = fabric_upstreamRequests_0_rv;
    (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:561.5-600.10" *)
    casez (_010_)
      /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:561.9-561.22" */
      1'h1:
        begin
          _000_ = 70'h0aaaaaaaaaaaaaaaaa;
          _001_ = 34'h0aaaaaaaa;
          _002_ = 1'h0;
          _003_ = 70'h0aaaaaaaaaaaaaaaaa;
          _004_ = 34'h0aaaaaaaa;
          _005_ = 1'h0;
          _006_ = 70'h0aaaaaaaaaaaaaaaaa;
        end
      /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:577.5-577.9" */
      default:
        begin
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:579.9-581.51" *)
          casez (\fabric_downstreamConnectors_0_fReq_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:579.13-579.53" */
            1'h1:
                _000_ = \fabric_downstreamConnectors_0_fReq_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:582.2-584.51" *)
          casez (\fabric_downstreamConnectors_0_fRes_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:582.6-582.46" */
            1'h1:
                _001_ = \fabric_downstreamConnectors_0_fRes_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:585.2-587.43" *)
          casez (\fabric_downstreamPending_0_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:585.6-585.38" */
            1'h1:
                _002_ = \fabric_downstreamPending_0_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:588.2-590.55" *)
          casez (\fabric_upstreamConnectors_0_inner_fReq_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:588.6-588.50" */
            1'h1:
                _003_ = \fabric_upstreamConnectors_0_inner_fReq_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:591.2-593.55" *)
          casez (\fabric_upstreamConnectors_0_inner_fRes_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:591.6-591.50" */
            1'h1:
                _004_ = \fabric_upstreamConnectors_0_inner_fRes_rv$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:594.2-596.55" *)
          casez (\fabric_upstreamConnectors_0_inner_pending$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:594.6-594.50" */
            1'h1:
                _005_ = \fabric_upstreamConnectors_0_inner_pending$D_IN ;
            default:
                /* empty */;
          endcase
          (* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:597.2-599.42" *)
          casez (\fabric_upstreamRequests_0_rv$EN )
            /* src = "bazel-out/k8-fastbuild/bin/boards/qf100/QF100/mkQF100Fabric.v:597.6-597.37" */
            1'h1:
                _006_ = \fabric_upstreamRequests_0_rv$D_IN ;
            default:
                /* empty */;
          endcase
        end
    endcase
  end
  always @(posedge CLK) begin
      fabric_downstreamConnectors_0_fReq_rv <= _000_;
      fabric_downstreamConnectors_0_fRes_rv <= _001_;
      fabric_downstreamPending_0_rv <= _002_;
      fabric_upstreamConnectors_0_inner_fReq_rv <= _003_;
      fabric_upstreamConnectors_0_inner_fRes_rv <= _004_;
      fabric_upstreamConnectors_0_inner_pending <= _005_;
      fabric_upstreamRequests_0_rv <= _006_;
  end
  assign cpu_ack_o = _011_;
  assign cpu_err_o = 1'h0;
  assign cpu_rty_o = 1'h0;
  assign cpu_dat_o = _098_;
  assign spi_cyc_o = _012_;
  assign spi_stb_o = _013_;
  assign spi_adr_o = _100_;
  assign spi_dat_o = _101_;
  assign spi_sel_o = _103_;
  assign spi_we_o = _015_;
  assign WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing_fast = _016_;
  assign WILL_FIRE_RL_fabric_upstreamConnectors_0_inner_process_outgoing = _018_;
  assign \MUX_fabric_upstreamConnectors_0_inner_pending$write_1__SEL_3  = _020_;
  assign \fabric_upstreamConnectors_0_inner_probeAck$PROBE  = _021_;
  assign \fabric_upstreamConnectors_0_inner_probeAck$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeAdr$PROBE  = cpu_adr_i;
  assign \fabric_upstreamConnectors_0_inner_probeAdr$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeCyc$PROBE  = cpu_cyc_i;
  assign \fabric_upstreamConnectors_0_inner_probeCyc$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeDataIn$PROBE  = cpu_dat_i;
  assign \fabric_upstreamConnectors_0_inner_probeDataIn$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeDataOut$PROBE  = _104_;
  assign \fabric_upstreamConnectors_0_inner_probeDataOut$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeSel$PROBE  = cpu_sel_i;
  assign \fabric_upstreamConnectors_0_inner_probeSel$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeStb$PROBE  = cpu_stb_i;
  assign \fabric_upstreamConnectors_0_inner_probeStb$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_probeWe$PROBE  = cpu_we_i;
  assign \fabric_upstreamConnectors_0_inner_probeWe$PROBE_VALID  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_incoming$wget  = { cpu_adr_i, cpu_we_i, cpu_dat_i, cpu_sel_i };
  assign \fabric_upstreamConnectors_0_inner_incoming$whas  = _022_;
  assign \fabric_upstreamConnectors_0_inner_outgoing$wget  = { 1'h1, \fabric_upstreamConnectors_0_inner_fRes_rv$port1__read [32:0] };
  assign \fabric_upstreamConnectors_0_inner_outgoing$whas  = _091_;
  assign \fabric_downstreamConnectors_0_outgoing$wget  = { 1'h1, \fabric_downstreamConnectors_0_fReq_rv$port1__read [68:0] };
  assign \fabric_downstreamConnectors_0_incoming$wget  = _106_;
  assign \fabric_downstreamConnectors_0_incoming$whas  = _093_;
  assign \fabric_upstreamConnectors_0_inner_fReq_rv$port0__write_1  = { 1'h1, \fabric_upstreamConnectors_0_inner_incoming$wget  };
  assign \fabric_upstreamConnectors_0_inner_fReq_rv$port1__read  = _107_;
  assign \fabric_upstreamConnectors_0_inner_fReq_rv$EN_port1__write  = _025_;
  assign \fabric_upstreamConnectors_0_inner_fReq_rv$port2__read  = _108_;
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$EN_port0__write  = _027_;
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$port0__write_1  = { 1'h1, \fabric_downstreamConnectors_0_fRes_rv$port1__read [32:0] };
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$port1__read  = _109_;
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$EN_port1__write  = _094_;
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$port2__read  = _110_;
  assign \fabric_downstreamConnectors_0_fReq_rv$EN_port0__write  = _030_;
  assign \fabric_downstreamConnectors_0_fReq_rv$port0__write_1  = { 21'h100000, \fabric_upstreamRequests_0_rv$port1__read [48:0] };
  assign \fabric_downstreamConnectors_0_fReq_rv$port1__read  = _111_;
  assign \fabric_downstreamConnectors_0_fReq_rv$EN_port1__write  = _033_;
  assign \fabric_downstreamConnectors_0_fReq_rv$port2__read  = _112_;
  assign \fabric_downstreamConnectors_0_fRes_rv$EN_port0__write  = _036_;
  assign \fabric_downstreamConnectors_0_fRes_rv$port0__write_1  = { 1'h1, _073_, \fabric_downstreamConnectors_0_incoming$wget [31:0] };
  assign \fabric_downstreamConnectors_0_fRes_rv$port1__read  = _113_;
  assign \fabric_downstreamConnectors_0_fRes_rv$EN_port1__write  = _038_;
  assign \fabric_downstreamConnectors_0_fRes_rv$port2__read  = _114_;
  assign \fabric_upstreamRequests_0_rv$EN_port0__write  = _039_;
  assign \fabric_upstreamRequests_0_rv$port0__write_1  = { 1'h1, \fabric_upstreamConnectors_0_inner_fReq_rv$port1__read [68:0] };
  assign \fabric_upstreamRequests_0_rv$port1__read  = _115_;
  assign \fabric_upstreamRequests_0_rv$EN_port1__write  = _042_;
  assign \fabric_upstreamRequests_0_rv$port2__read  = _116_;
  assign \fabric_downstreamPending_0_rv$EN_port0__write  = _045_;
  assign \fabric_downstreamPending_0_rv$port1__read  = _095_;
  assign \fabric_downstreamPending_0_rv$EN_port1__write  = _047_;
  assign \fabric_downstreamPending_0_rv$port2__read  = _048_;
  assign \fabric_downstreamConnectors_0_fReq_rv$D_IN  = \fabric_downstreamConnectors_0_fReq_rv$port2__read ;
  assign \fabric_downstreamConnectors_0_fReq_rv$EN  = 1'h1;
  assign \fabric_downstreamConnectors_0_fRes_rv$D_IN  = \fabric_downstreamConnectors_0_fRes_rv$port2__read ;
  assign \fabric_downstreamConnectors_0_fRes_rv$EN  = 1'h1;
  assign \fabric_downstreamPending_0_rv$D_IN  = \fabric_downstreamPending_0_rv$port2__read ;
  assign \fabric_downstreamPending_0_rv$EN  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_fReq_rv$D_IN  = \fabric_upstreamConnectors_0_inner_fReq_rv$port2__read ;
  assign \fabric_upstreamConnectors_0_inner_fReq_rv$EN  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$D_IN  = \fabric_upstreamConnectors_0_inner_fRes_rv$port2__read ;
  assign \fabric_upstreamConnectors_0_inner_fRes_rv$EN  = 1'h1;
  assign \fabric_upstreamConnectors_0_inner_pending$D_IN  = _049_;
  assign \fabric_upstreamConnectors_0_inner_pending$EN  = _097_;
  assign \fabric_upstreamRequests_0_rv$D_IN  = \fabric_upstreamRequests_0_rv$port2__read ;
  assign \fabric_upstreamRequests_0_rv$EN  = 1'h1;
endmodule

